export const metadata = {
  title: 'Next.js Tutorial',
  description: 'Generated by Next.js for el',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
